server:
  port: 8761

eureka:
  client:
    registerWithEureka: false  #this will help this to not register itself to client
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
  instance:
    hostname: localhost
